spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
sms:
  toast:
    url: https://api-sms.cloud.toast.com/
    app-key: ENC(6RJ/b4qil0Y8tFxhSnIMZQvmxzCrEEw7DAx2uZ3x6W668sB6sxQ3SNgBj5lxiG6yD4n4NPgr2lZPEEVrbUlBlg==)
    secret-key: ENC(ab1yfScRuzyplJ3e2xpdYX8qW5j4ZBjwmG4nKekbVp1NdJ/zV9BL7UO8P/68lrB9)