spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test;
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update