spring:
  profiles:
    group:
      local: swagger
      develop: swagger
      production:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ENC(Y/ZTOcvtPL8kc0hzWrognP25n7Xc1sdpAKV8J6LtKVt3D5jVDbvRiJNiKlO7QlaCN1UcRtQsa3nuiESvzimVvw==)